# Generated by Django 5.0.4 on 2024-08-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='Instructions not provided'),
        ),
    ]
